services:
  web:
    build: .
    container_name: php-apache
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:9.3.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Providence
      MYSQL_USER: providence
      MYSQL_PASSWORD: bb1wy
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  db_data:
